INSERT INTO venue (VenueName, Location)
VALUES ('Australian Grand Prix', 'Melbourne/Australia'),
       ('Bahrain Grand Prix', 'Sakhir/Bahrain'),
       ('Chinese Grand Prix', 'Shanghai/China'),
       ('Dutch Grand Prix', 'Zandvoort/Netherlands'),
       ('Italian Grand Prix', 'Monza/Italy'),
       ('Belgian Grand Prix', 'Spa-Francorchamps/Belgium'),
       ('Hungarian Grand Prix', 'Budapest/Hungary'),
       ('British Grand Prix', 'Silverstone/United Kingdom'),
       ('Portuguese Grand Prix', 'Algarve/Portugal'),
       ('Spanish Grand Prix', 'Barcelona/Spain'),
       ('Monaco Grand Prix', 'Monaco/Monaco'),
       ('Azerbaijan Grand Prix', 'Baku/Azerbaijan'),
       ('Canadian Grand Prix', 'Montreal/Canada'),
       ('French Grand Prix', 'Le Castellet/France'),
       ('Austrian Grand Prix', 'Spielberg/Austria'),
       ('Hungarian Grand Prix', 'Budapest/Hungary'),
       ('Singapore Grand Prix', 'Singapore/Singapore'),
       ('United States Grand Prix', 'Austin/USA'),
       ('Mexican Grand Prix', 'Mexico City/Mexico'),
       ('Brazilian Grand Prix', 'Sao Paulo/Brazil'),
       ('Qatar Grand Prix', 'Losail/Qatar'),
       ('Saudi Arabian Grand Prix', 'Jeddah/Saudi Arabia'),
       ('Abu Dhabi Grand Prix', 'Yas Marina/UAE');